export default [
  "/start",
  "start",
  // "buy info",
  // "/buyinfo",
  "check balance",
  "/checkbalance",
  "fund wallet",
  "/fundwallet",
  "show",
  "/show",
  "🔴hide keyboard",
  "/hide",
  // "my documents",
  // "/mydocuments",
];
