export default [
  "/start",
  "start",
  "buy document",
  "/buyinfo",
  "check balance",
  "/checkbalance",
  "fund wallet",
  "/fundwallet",
  "show",
  "/show",
  "🔴hide keyboard",
  "/hide",
  "my documents",
  "/mydocuments",
  "create account",
  "/about bot ?",
  "get number for otp code",
  "/getotp",
  "check countries available",
  "check services available",
  "select country",
  "select service",
  "use a number",
  "use this number",
  "don't use number",
  "about bot ?",
];
