export default [
  "/start",
  "start",
  "buy document",
  "/buyinfo",
  "Check balance",
  "/checkbalance",
  "Fund wallet",
  "/fundwallet",
  "show",
  "/show",
  "🔴Hide keyboard",
  "/hide",
  "my documents",
  "/mydocuments",
  "create account",
  "/About bot ?",
  "/country",
  "/service",
  "get number for otp code",
  "/getotp",
  "Check countries available",
  "Check services available",
  "Select country",
  "Select service",
  "Use a number",
  "Use this number",
  "Don't use this number",
  "Profile details",
  "/profile",
  "About bot ?",
  "rent",
  "otu",
  "month",
  "week",
];
